#!/bin/bash
REPO="http://192.168.1.143:88"
INSTALL_PATH=/mnt
# Version 1.1
# DO NOT Use this version (git) on an actual tucana system without changing the INSTALL_PATH to / and the REPO_PATH
if [[ $EUID -ne 0 ]]; then
   echo "This package manager must be run as root" 
   exit 1
fi


check_online() {

   cd /tmp
   wget $REPO/available-packages/sha256 &> /dev/null
   if [[ $? != 0 ]]; then
     echo "ERROR: Server not reachable or doesn't contain repo files"
     exit 1
   fi


}

move() {
   # This function is so that if packages or files have to be overwriten, the system does not crash while doing it, mostly for updating 
   local folpath=$1
   local files
   local folders

   
   cd $folpath
   
   folders=$(find . -type d | tail -n +2 | cut -c2- | sed "s|^|$INSTALL_PATH|" | tr "\n" " ")

   mkdir -p $folders
   
   files=$(find . -type l -o -type f ! -name 'postinst')

   IFS=$'\n'
   for file in $files; do
       mv  $file $(echo $file | cut -c2- | sed "s|^|$INSTALL_PATH|g")
   done
   unset IFS
   cd $INSTALL_PATH/var/cache/mercury
}


update_package() {
    local PACKAGE=$1
        cd $INSTALL_PATH/var/cache/mercury
        echo "$REPO/packages/$PACKAGE.tar.xz"
        echo "Downloading $PACKAGE"

        wget -O $INSTALL_PATH/var/cache/mercury/$PACKAGE.tar.xz $REPO/packages/$PACKAGE.tar.xz

        echo "Updating $PACKAGE..."
        echo "Extracting $PACKAGE..."
        tar -xpf $PACKAGE.tar.xz

        echo "Copying contents..."
        move $PACKAGE
        #Check if postinst exists
         if [ -f $PACKAGE/postinst ]; then
            echo "Running Post Install Script..."
            bash $PACKAGE/postinst 
         fi
        echo  "Removing Cache"
        rm -rf $INSTALL_PATH/var/cache/mercury/$PACKAGE*
}

# Check Online
check_online

# Get all the available updates
updates=$(diff $INSTALL_PATH/var/cache/mercury/current $INSTALL_PATH/var/cache/mercury/sha256|grep ">"|cut -c 3- | cut -c67- | sed 's|.tar.xz||g')

# Organize the updates to make sure that only packages that are installed are updated 

updates=$(echo "$updates" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-) 
for package in ${updates[@]}
do
  if cat $INSTALL_PATH/etc/installed_package | grep -x $package; then
     updates_curated="$updates_curated $package"
  fi
done

# Sanity check to make sure that there are actually updates avaliable
numupdate=$(wc -w <<< $updates_curated)
if [[ $numupdate == 0 ]]; then
   echo "No updates found, try to sync"
   exit 0
fi
 


# Install the updates

echo "Packages to be updated $updates_curated"
 read -r -p "Would you like to continue? [Y/n] " confirmation

case $confirmation in
     "" | Y | y)
 echo "Continuing with install of $numpackage packages"
 for package in ${updates_curated[@]}; do
    update_package "$package"
 done
 cp -v $INSTALL_PATH/var/cache/mercury/sha256  $INSTALL_PATH/var/cache/mercury/current

 ;;
     *)
 echo "Aborting Invalid Input!"
 ;;
esac



  
  
