#!/bin/bash
REPO="http://192.168.1.143:88"
INSTALL_PATH=/mnt
#Version 1.0-Prerelease2

if [[ $EUID -ne 0 ]]; then
   echo "This package manager must be run as root" 
   exit 1
fi

install_package() {
    local PACKAGE=$1
    if cat $INSTALL_PATH/etc/installed_package | grep -x $PACKAGE; then
        echo "$PACKAGE is already installed, skipping"
        return 1
    else
        mkdir -p $INSTALL_PATH/var/cache/mercury
        cd $INSTALL_PATH/var/cache/mercury
        echo "$REPO/packages/$PACKAGE.tar.xz"
        echo "Downloading $PACKAGE"

        wget -O $INSTALL_PATH/var/cache/mercury/$PACKAGE.tar.xz $REPO/packages/$PACKAGE.tar.xz

        echo "Installing $PACKAGE..."
        echo "Extracting $PACKAGE..."
        tar -xpf $PACKAGE.tar.xz

        echo "Copying contents..."
        cp -rp $PACKAGE/* $INSTALL_PATH
        #Check if postinst exists
         if [ -f $PACKAGE/postinst ]; then
            echo "Running Post Install Script..."
            # bash $PACKAGE/postinst 
         fi
        echo $PACKAGE >> $INSTALL_PATH/etc/installed_package
        echo  "Removing Cache"
        rm -rf $INSTALL_PATH/var/cache/mercury/$PACKAGE*
    fi
}
packages=$@
current=0

for package in ${packages[@]}
do
   if [[ $(cat $INSTALL_PATH/var/cache/mercury/available-packages | grep -x $package | wc -c) == 0 ]]
   then
	   echo "$package was not found, exiting"
	   exit 1
   fi
done


echo "Getting Dependencies"
until [ "$packages" == "$packageold" ] 
do
 packageold=$packages
 for package in ${packages[@]}
 do
     if cat $INSTALL_PATH/etc/installed_package | grep -x $package >/dev/null; then
	     :
     else
         packages="$packages $(cat $INSTALL_PATH/var/cache/mercury/depend/depend-$package)"
         packages=$( awk 'BEGIN{RS=ORS=" "}!a[$0]++' <<<$packages );
     fi
 done
 ((current++))
# echo $current
done

#Get rid of repeats (also in depend check)
packages=$( awk 'BEGIN{RS=ORS=" "}!a[$0]++' <<<$packages );
#Take the mutliline packages bariable and convert it to a single line
packages=$(echo "$packages" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-) 


numpackage=$(wc -w <<< $packages)
#Basically the same thing but just for safety lol
pkgnoline=$(tr "\n" " " <<< $packages)

#Sanity check to make sure that all packages exist (Same as above)
for package in ${packages[@]}
do
   if [[ $(cat $INSTALL_PATH/var/cache/mercury/available-packages | grep -x $package | wc -c) == 0 ]]
   then
	   echo "$package was not found, exiting"
	   exit 1
   fi
done

#Sanity check to make sure that the root package is not already installed
#echo $numpackage
#if [[ numpackage == 1 ]]; then
#	if cat $INSTALL_PATH/etc/installed_package | grep -x $packages; then
#		echo "All packages have been installed"
#		exit 0
#	fi
#fi
if test $numpackage -ne 0; then
 printf "\n\nPackages to be installed: $pkgnoline\n"
 read -r -p "$numpackage packages are queued to install, would you like to continue? [Y/n] " confirmation

 case $confirmation in
      "" | Y | y)
  echo "Continuing with install of $numpackage packages"
  for package in ${packages[@]}
  do
      install_package "$package"
  done

  ;;
   *)
  echo "Aborting Invalid Input!"
  ;;
 esac
 else 
  echo $numpackage
  printf "\n\nNothing to do all packages are installed\n"
fi


